### ISSUE TITLE
Support Null-Move in Parser

### ISSUE THREAD

**Issue by pb00068** [DHTMLGoodies/chessParser#2]
Yesterday I tested the chessparser in order to get the fen-code of the final position in various games. While testing I came across a game containing a Null Move in the main variation and this made the parser abort prematurely on following move 49. Re6+.
Although a Null Move (represented by <> or --, in this case it was --) according definition (http://www.enpassant.dk/chess/palview/manual/pgn.htm) should only appear inside a variation, several PGN-Software today allow it also on the main variation. In that particular game (see below) probably the move was simply not readable from score sheet and was anyhow not a relevant move.
It would be nice if also your parser would accomplish with Null-Moves

thanks & regards
Guenther
1. c4 e5 2. Nc3 Nf6 3. g3 c6 4. d4 exd4 5. Qxd4 d5 6. cxd5 cxd5 7. Nf3 Nc6 8. Qd1 Be7 9. Bg2 O-O 10. O-O Be6 11. Nb5 a6 12. Nbd4 Qd7 13. Ng5 Nxd4 14. Qxd4 Rac8 15. Rd1 h6 16. Nxe6 fxe6 17. Bh3 Bc5 18. Qd3 Bxf2+ 19. Kxf2 Ne4+ 20. Kg1 Nf2 21. Bxe6+ Qxe6 22. Qxd5 Nh3+ 23. Kh1 Rf1+ 24. Kg2 Rf2+ 25. Kh1 Qxd5+ 26. Rxd5 Rxe2 27. Bd2 Rf8 28. Re1 Rxe1+ 29. Bxe1 Rf1+ 30. Kg2 Rxe1 31. Kxh3 Re2 32. a4 Rxb2 33. a5 Rb5 34. Rd7 g5 35. Kg4 Kf8 36. Kh5 Ke8 37. Rh7 Kd8 38. Kxh6 Kc8 39. h4 gxh4 40. gxh4 Rxa5 41. h5 Ra1 42. Kg7 Rg1+ 43. Kf8 a5 44. h6 Rd1 45. Re7 Rh1 46. h7 Kb8 47. Kg7 Ka7 48. -- Ka6 49. Re6+ b6 50. Rh6 Rg1+ 51. Kf7 Rf1+ 52. Ke7 Re1+ 53. Kd7 Rd1+ 54. Kc7 Rc1+ 55. Kb8 a4 56. h8=Q Ka5 57. Qb2 1-0

[17-Apr-2014 08:18:42 Europe/Rome] PHP Fatal error:  Uncaught exception 'Exception' with message 'Fen: 8/kp2R2P/K7/p7/8/8/8/7r b - - 4 48
color: black
notation: Re6
Rank:
File:
0, ' in /home/gchess/public_html/test/chessParser-master/FenParser0x88.php:991
Stack trace:
#0 /home/gchess/public_html/test/chessParser-master/FenParser0x88.php(833): FenParser0x88->getFromAndToByNotation('Re6+')
#1 /home/gchess/public_html/test/chessParser-master/GameParser.php(50): FenParser0x88->getParsed(Array)
#2 /home/gchess/public_html/test/chessParser-master/GameParser.php(34): GameParser->parseAMove(Array)
#3 /home/gchess/public_html/test/chessParser-master/GameParser.php(21): GameParser->parseMoves(Array)
#4 /home/gchess/public_html/test/chessParser-master/PgnParser.php(117): GameParser->getParsedGame(Array)
#5 /home/gchess/public_html/test/chessParser-master/PgnParser.php(98): PgnParser->getParsedGame('[Event "Arco Op...')
#6 /home/gchess/public_html/test/chessParser-master/PgnParser.php(92): PgnParser->getGameByIndex(0)
#7 /home/gchess/public_html/test/test2.php(44): PgnPars in /home/gchess/public_html/test/chessParser-master/FenParser0x88.php on line 991

**Comment by DHTMLGoodies** [comment]
Support for Null moves should now work.
